export const CLUBS_DATA = [
  {
    slug: 'microsoft-club',
    name: 'Microsoft Club',
    description: 'Empowering students with Microsoft technologies, Azure cloud, and developer tools to build real-world solutions.',
    mission: 'To bridge academia and industry through Microsoft\'s ecosystem of tools and services.',
    department: 'Computer Science',
    theme: 'theme-microsoft',
    accentColor: '#00A4EF',
    icon: 'Monitor',
    gradient: 'from-blue-500 to-cyan-600',
    bg: 'bg-blue-500',
    image: '/images/clubs/microsoft-club.jpg',
  },
  {
    slug: 'music-dance-club',
    name: 'Music & Dance Club',
    description: 'A vibrant community for artists, musicians, and dancers to express, perform, and grow together.',
    mission: 'To nurture performing arts culture and give every artist a stage.',
    department: 'Cultural Affairs',
    theme: 'theme-music',
    accentColor: '#EC4899',
    icon: 'Music',
    gradient: 'from-pink-500 to-rose-600',
    bg: 'bg-pink-500',
    image: '/images/clubs/music-dance-club.jpg',
  },
  {
    slug: 'event-management-club',
    name: 'Event Management Club',
    description: 'The masterminds behind BEC\'s biggest events — organizing fests, competitions, and inter-college meets.',
    mission: 'To create unforgettable experiences and develop world-class event management skills.',
    department: 'Student Affairs',
    theme: 'theme-events',
    accentColor: '#F59E0B',
    icon: 'Star',
    gradient: 'from-amber-500 to-orange-600',
    bg: 'bg-amber-500',
    image: '/images/clubs/event-management-club.jpg',
  },
  {
    slug: 'sports-health-club',
    name: 'Sports & Health Club',
    description: 'Promoting physical fitness, sports excellence, and a healthy campus lifestyle for all students.',
    mission: 'To build champions in sports and advocates for health and wellness.',
    department: 'Physical Education',
    theme: 'theme-sports',
    accentColor: '#10B981',
    icon: 'Dumbbell',
    gradient: 'from-green-500 to-emerald-600',
    bg: 'bg-green-500',
    image: '/images/clubs/sports-health-club.png',
  },
  {
    slug: 'media-club',
    name: 'Media Club',
    description: 'Capturing campus life through the lens — photography, videography, journalism, and digital content creation.',
    mission: 'To tell BEC\'s story through powerful visual and written narratives.',
    department: 'Media & Communications',
    theme: 'theme-media',
    accentColor: '#A855F7',
    icon: 'Camera',
    gradient: 'from-purple-500 to-violet-600',
    bg: 'bg-purple-500',
    image: '/images/clubs/media-club.jpg',
  },
  {
    slug: 'startup-internship-club',
    name: 'Startup & Internship Club',
    description: 'Connecting students with startup opportunities, internships, and entrepreneurship resources.',
    mission: 'To turn student ideas into funded startups and careers into opportunities.',
    department: 'Entrepreneurship Cell',
    theme: 'theme-startup',
    accentColor: '#F97316',
    icon: 'Rocket',
    gradient: 'from-orange-500 to-red-500',
    bg: 'bg-orange-500',
    image: '/images/clubs/startup-internship-club.jpg',
  },
  {
    slug: 'social-environmental-club',
    name: 'Social & Environmental Club',
    description: 'Leading sustainability initiatives, social impact projects, and community outreach on and off campus.',
    mission: 'To create socially responsible engineers who care for people and the planet.',
    department: 'Social Responsibility',
    theme: 'theme-social',
    accentColor: '#14B8A6',
    icon: 'Leaf',
    gradient: 'from-teal-500 to-cyan-600',
    bg: 'bg-teal-500',
    image: '/images/clubs/social-environmental-club.jpg',
  },
  {
    slug: 'placement-club',
    name: 'Placement Club',
    description: 'Preparing BEC students for industry with mock interviews, resume workshops, and corporate connections.',
    mission: 'To maximize placement opportunities and make every student industry-ready.',
    department: 'Training & Placement',
    theme: 'theme-placement',
    accentColor: '#1E3A8A',
    icon: 'Briefcase',
    gradient: 'from-blue-800 to-indigo-900',
    bg: 'bg-blue-900',
    image: '/images/clubs/placement-club.jpg',
  },
] as const;
